import psycopg2
import os
import uuid
import random
from datetime import datetime, timedelta

DATABASE_URL = os.environ.get("DATABASE_URL")

TASK_DEFINITIONS = [
    # ── EOD / Settlement chain ─────────────────────────────────────────────
    (
        "EOD-SETTL-INIT",
        "daily",
        "18:00",
        60,
        120,
        "Initialize end-of-day settlement run",
    ),
    (
        "EOD-SETTL-VALIDATE",
        "daily",
        "18:05",
        90,
        180,
        "Validate all open trade positions",
    ),
    ("EOD-SETTL-CALC", "daily", "18:20", 120, 300, "Calculate net settlement amounts"),
    ("EOD-SETTL-POST", "daily", "18:45", 60, 120, "Post settlement entries to GL"),
    (
        "EOD-SETTL-CONFIRM",
        "daily",
        "19:00",
        30,
        60,
        "Generate settlement confirmation reports",
    ),
    ("EOD-SETTL-ARCHIVE", "daily", "19:10", 45, 90, "Archive settlement run artifacts"),
    (
        "EOD-SETTL-NOTIFY",
        "daily",
        "19:20",
        10,
        30,
        "Send settlement completion notifications",
    ),
    ("EOD-SETTL-AUDIT", "daily", "19:30", 30, 60, "Write settlement audit trail"),
    # ── Nightly GL close ───────────────────────────────────────────────────
    (
        "NIGHTLY-GL-EXTRACT",
        "daily",
        "20:00",
        90,
        240,
        "Extract general ledger transactions",
    ),
    ("NIGHTLY-GL-BALANCE", "daily", "20:30", 60, 180, "Verify GL debit/credit balance"),
    (
        "NIGHTLY-GL-CLOSE",
        "daily",
        "21:00",
        120,
        360,
        "Execute nightly GL close procedure",
    ),
    (
        "NIGHTLY-GL-REPORT",
        "daily",
        "21:45",
        60,
        120,
        "Produce nightly GL summary report",
    ),
    ("NIGHTLY-GL-REPOST", "daily", "22:15", 30, 90, "Repost any suspended GL entries"),
    ("NIGHTLY-GL-LOCK", "daily", "22:30", 10, 30, "Lock GL period for current day"),
    # ── Payroll processing ─────────────────────────────────────────────────
    (
        "PAYRL-CALC-GROSS",
        "weekly",
        "06:00",
        120,
        300,
        "Calculate gross pay for all employees",
    ),
    (
        "PAYRL-CALC-TAX",
        "weekly",
        "06:30",
        90,
        240,
        "Apply federal and state tax withholding",
    ),
    (
        "PAYRL-CALC-DEDUCT",
        "weekly",
        "07:00",
        60,
        180,
        "Process 401k and benefit deductions",
    ),
    (
        "PAYRL-DIRECT-DEP",
        "weekly",
        "07:30",
        120,
        300,
        "Initiate ACH direct deposit file",
    ),
    ("PAYRL-STUB-GEN", "weekly", "08:00", 60, 120, "Generate employee pay stub PDFs"),
    (
        "PAYRL-AUDIT-LOG",
        "weekly",
        "08:30",
        30,
        60,
        "Write payroll audit trail to compliance DB",
    ),
    ("PAYRL-GARNISH-CALC", "weekly", "06:45", 30, 90, "Calculate wage garnishments"),
    (
        "PAYRL-BENEFITS-RECONCILE",
        "weekly",
        "09:00",
        60,
        150,
        "Reconcile benefits deductions to carrier",
    ),
    # ── ACH / Wire processing ──────────────────────────────────────────────
    ("ACH-INBOUND-PARSE", "daily", "07:00", 30, 90, "Parse inbound ACH file from Fed"),
    (
        "ACH-INBOUND-POST",
        "daily",
        "07:15",
        60,
        180,
        "Post inbound ACH credits to accounts",
    ),
    (
        "ACH-OUTBOUND-BUILD",
        "daily",
        "16:00",
        45,
        120,
        "Build outbound ACH transmission file",
    ),
    (
        "ACH-OUTBOUND-XMIT",
        "daily",
        "16:30",
        30,
        60,
        "Transmit outbound ACH file to Fed",
    ),
    (
        "ACH-OUTBOUND-ACK",
        "daily",
        "17:00",
        15,
        45,
        "Receive and validate ACH acknowledgment",
    ),
    ("ACH-RETURN-PROC", "daily", "08:00", 30, 90, "Process ACH return items"),
    (
        "ACH-NOC-HANDLE",
        "daily",
        "08:30",
        20,
        60,
        "Handle Notification of Change records",
    ),
    (
        "WIRE-CUTOFF-SWEEP",
        "daily",
        "17:30",
        60,
        120,
        "Sweep pending wires before cutoff",
    ),
    (
        "WIRE-CONFIRM-RECV",
        "daily",
        "18:00",
        15,
        45,
        "Receive wire confirmation messages",
    ),
    ("WIRE-RECONCILE", "daily", "18:30", 45, 90, "Reconcile outbound wires to GL"),
    # ── Customer data pipelines ────────────────────────────────────────────
    ("CUST-SYNC-CRM", "daily", "02:00", 60, 180, "Sync customer master from CRM to DW"),
    (
        "CUST-DEDUP-RUN",
        "daily",
        "02:30",
        120,
        360,
        "Run deduplication on customer records",
    ),
    (
        "CUST-SCORE-UPDATE",
        "daily",
        "03:00",
        90,
        240,
        "Recalculate customer risk scores",
    ),
    ("CUST-SEGMENT-RUN", "daily", "03:30", 60, 180, "Re-assign customers to segments"),
    (
        "CUST-EMAIL-PREP",
        "daily",
        "04:00",
        30,
        90,
        "Prepare customer email suppression list",
    ),
    (
        "CUST-PROFILE-EXPORT",
        "daily",
        "04:30",
        60,
        120,
        "Export customer profiles to S3",
    ),
    (
        "CUST-ADDRESS-VERIFY",
        "weekly",
        "03:00",
        60,
        180,
        "Verify and standardize customer addresses",
    ),
    (
        "CUST-CONSENT-SYNC",
        "daily",
        "05:00",
        20,
        60,
        "Sync marketing consent flags from preference center",
    ),
    (
        "CUST-ONBOARD-STATUS",
        "daily",
        "06:00",
        15,
        45,
        "Update onboarding funnel status",
    ),
    # ── Inventory / Warehouse ──────────────────────────────────────────────
    (
        "INV-COUNT-RECV",
        "daily",
        "05:00",
        45,
        120,
        "Receive inventory count feeds from WMS",
    ),
    (
        "INV-REORDER-CALC",
        "daily",
        "05:30",
        60,
        180,
        "Calculate reorder points and quantities",
    ),
    (
        "INV-ALLOC-UPDATE",
        "daily",
        "06:00",
        30,
        90,
        "Update warehouse allocation records",
    ),
    (
        "INV-VARIANCE-RPT",
        "daily",
        "06:30",
        45,
        90,
        "Generate inventory variance report",
    ),
    ("INV-VALUATION-RUN", "daily", "07:00", 90, 240, "Run FIFO inventory valuation"),
    ("INV-SHRINK-CALC", "weekly", "08:00", 60, 120, "Calculate shrinkage by location"),
    (
        "INV-CYCLE-COUNT-SCHED",
        "weekly",
        "07:00",
        30,
        60,
        "Schedule cycle count assignments",
    ),
    (
        "INV-TRANSFER-RECONCILE",
        "daily",
        "07:30",
        45,
        90,
        "Reconcile inter-warehouse transfer orders",
    ),
    (
        "INV-EXPIRY-SWEEP",
        "daily",
        "08:00",
        20,
        60,
        "Flag inventory approaching expiry date",
    ),
    # ── Reporting chain ────────────────────────────────────────────────────
    (
        "RPT-SALES-DAILY",
        "daily",
        "06:00",
        60,
        180,
        "Generate daily sales summary report",
    ),
    ("RPT-SALES-REGION", "daily", "06:30", 45, 120, "Break down sales by region"),
    (
        "RPT-MARGIN-CALC",
        "daily",
        "07:00",
        60,
        180,
        "Calculate gross margin by product line",
    ),
    ("RPT-EXEC-DASH", "daily", "07:30", 30, 60, "Populate executive dashboard metrics"),
    ("RPT-BOARD-PKG", "weekly", "08:00", 90, 180, "Compile board reporting package"),
    (
        "RPT-REGULATOR-SUBMIT",
        "monthly",
        "09:00",
        120,
        300,
        "Submit regulatory reporting package",
    ),
    (
        "RPT-CHANNEL-PERF",
        "daily",
        "07:45",
        30,
        90,
        "Report sales performance by channel",
    ),
    (
        "RPT-PRODUCT-SELL-THRU",
        "daily",
        "08:00",
        45,
        120,
        "Calculate product sell-through rates",
    ),
    (
        "RPT-FORECAST-VARIANCE",
        "weekly",
        "09:00",
        60,
        180,
        "Report forecast vs actuals variance",
    ),
    # ── ETL pipelines ─────────────────────────────────────────────────────
    (
        "ETL-TRANS-EXTRACT",
        "daily",
        "01:00",
        90,
        240,
        "Extract transaction records from OLTP",
    ),
    (
        "ETL-TRANS-TRANSFORM",
        "daily",
        "01:45",
        120,
        360,
        "Transform and cleanse transaction data",
    ),
    ("ETL-TRANS-LOAD", "daily", "02:30", 60, 180, "Load transformed records to DW"),
    (
        "ETL-ACCT-EXTRACT",
        "daily",
        "01:15",
        60,
        180,
        "Extract account balances from core",
    ),
    (
        "ETL-ACCT-TRANSFORM",
        "daily",
        "02:00",
        90,
        240,
        "Transform account data for analytics",
    ),
    ("ETL-ACCT-LOAD", "daily", "02:45", 60, 120, "Load account data to DW"),
    ("ETL-PROD-EXTRACT", "daily", "00:30", 60, 150, "Extract product catalog changes"),
    ("ETL-PROD-LOAD", "daily", "01:00", 45, 90, "Load product updates to DW"),
    (
        "ETL-EVENT-STREAM-LOAD",
        "daily",
        "03:00",
        60,
        180,
        "Load clickstream events to DW",
    ),
    ("ETL-REFDATA-SYNC", "daily", "00:15", 20, 60, "Sync reference data tables to DW"),
    (
        "ETL-CURRENCY-RATES",
        "daily",
        "00:45",
        15,
        45,
        "Load daily FX rates into rate table",
    ),
    # ── Backup / Archival ──────────────────────────────────────────────────
    ("BKP-DB-FULL", "weekly", "22:00", 180, 540, "Full database backup to tape"),
    ("BKP-DB-INCR", "daily", "23:00", 60, 180, "Incremental database backup"),
    (
        "BKP-LOGS-ROTATE",
        "daily",
        "23:30",
        30,
        60,
        "Rotate and compress application logs",
    ),
    (
        "BKP-VERIFY-RESTORE",
        "weekly",
        "23:00",
        120,
        300,
        "Verify backup integrity via test restore",
    ),
    (
        "BKP-OFFSITE-XFER",
        "weekly",
        "01:00",
        120,
        300,
        "Transfer backup tapes to offsite vault",
    ),
    (
        "BKP-CATALOG-UPDATE",
        "daily",
        "23:45",
        15,
        45,
        "Update backup catalog with run metadata",
    ),
    (
        "ARCH-TRANS-7YR",
        "monthly",
        "02:00",
        180,
        480,
        "Archive transactions older than 7 years",
    ),
    (
        "ARCH-STMTS-PURGE",
        "monthly",
        "03:00",
        90,
        240,
        "Purge expired customer statements",
    ),
    (
        "ARCH-AUDIT-COMPRESS",
        "monthly",
        "04:00",
        60,
        180,
        "Compress and archive audit log files",
    ),
    # ── Fraud / Risk ───────────────────────────────────────────────────────
    (
        "FRAUD-SCORE-BATCH",
        "daily",
        "03:00",
        120,
        360,
        "Batch fraud scoring on overnight transactions",
    ),
    (
        "FRAUD-WATCHLIST-UPD",
        "daily",
        "03:30",
        30,
        90,
        "Update OFAC and watchlist tables",
    ),
    (
        "FRAUD-ALERT-DISTRIB",
        "daily",
        "04:00",
        45,
        90,
        "Distribute fraud alerts to case management",
    ),
    (
        "FRAUD-MODEL-REFRESH",
        "weekly",
        "01:00",
        240,
        600,
        "Refresh fraud detection model weights",
    ),
    ("FRAUD-CASE-AGING", "daily", "09:00", 20, 60, "Age open fraud cases and escalate"),
    (
        "FRAUD-DISPUTE-INTAKE",
        "daily",
        "10:00",
        30,
        90,
        "Process incoming fraud dispute filings",
    ),
    ("RISK-VAR-CALC", "daily", "19:00", 90, 240, "Calculate portfolio Value-at-Risk"),
    (
        "RISK-STRESS-TEST",
        "weekly",
        "20:00",
        180,
        480,
        "Run regulatory stress test scenarios",
    ),
    (
        "RISK-LIMIT-CHECK",
        "daily",
        "18:30",
        30,
        60,
        "Check trading desk limit utilization",
    ),
    (
        "RISK-CONCENTRATION",
        "daily",
        "19:30",
        45,
        120,
        "Analyze portfolio concentration risk",
    ),
    (
        "RISK-COUNTERPARTY",
        "daily",
        "20:00",
        60,
        180,
        "Score counterparty credit exposure",
    ),
    # ── Compliance / Regulatory ────────────────────────────────────────────
    (
        "COMPL-SAR-COMPILE",
        "weekly",
        "09:00",
        90,
        240,
        "Compile Suspicious Activity Reports",
    ),
    (
        "COMPL-CTR-SUBMIT",
        "daily",
        "10:00",
        45,
        120,
        "Submit Currency Transaction Reports",
    ),
    (
        "COMPL-AML-SCREEN",
        "daily",
        "04:00",
        120,
        300,
        "Anti-money laundering screening run",
    ),
    (
        "COMPL-KYC-REFRESH",
        "monthly",
        "06:00",
        180,
        480,
        "Refresh KYC documentation index",
    ),
    (
        "COMPL-AUDIT-TRAIL",
        "daily",
        "23:00",
        30,
        60,
        "Write daily compliance audit trail",
    ),
    (
        "COMPL-GDPR-PURGE",
        "monthly",
        "02:00",
        90,
        240,
        "Execute GDPR data deletion requests",
    ),
    ("COMPL-PCI-SCAN", "weekly", "01:00", 60, 180, "Run PCI-DSS compliance scan"),
    (
        "COMPL-SOX-EVIDENCE",
        "monthly",
        "10:00",
        120,
        300,
        "Collect SOX control evidence artifacts",
    ),
    # ── System maintenance ─────────────────────────────────────────────────
    ("SYS-HEALTH-CHECK", "daily", "00:00", 5, 15, "System-wide health check ping"),
    ("SYS-CACHE-FLUSH", "daily", "03:00", 10, 30, "Flush application cache layers"),
    (
        "SYS-CONN-POOL-RESET",
        "daily",
        "04:00",
        5,
        15,
        "Reset idle database connection pools",
    ),
    ("SYS-TEMP-PURGE", "daily", "05:00", 15, 45, "Purge temp tables and work files"),
    ("SYS-INDEX-REBUILD", "weekly", "01:00", 120, 360, "Rebuild fragmented DB indexes"),
    ("SYS-STATS-UPDATE", "weekly", "02:00", 60, 180, "Update DB optimizer statistics"),
    ("SYS-DISK-REPORT", "daily", "06:00", 5, 15, "Report disk utilization by volume"),
    ("SYS-CERT-CHECK", "weekly", "07:00", 10, 20, "Check SSL certificate expiry dates"),
    (
        "SYS-PATCH-COMPLIANCE",
        "weekly",
        "08:00",
        20,
        60,
        "Report OS patch compliance status",
    ),
    ("SYS-DEADLOCK-SCAN", "daily", "02:00", 10, 30, "Scan DB logs for deadlock events"),
    (
        "SYS-LONG-QUERY-RPT",
        "daily",
        "06:30",
        10,
        30,
        "Report queries exceeding runtime threshold",
    ),
    (
        "SYS-TABLESPACE-CHK",
        "daily",
        "07:00",
        10,
        20,
        "Check tablespace utilization thresholds",
    ),
    # ── Billing / Invoicing ────────────────────────────────────────────────
    (
        "BILL-USAGE-CALC",
        "monthly",
        "01:00",
        120,
        360,
        "Calculate customer usage for billing",
    ),
    (
        "BILL-INVOICE-GEN",
        "monthly",
        "03:00",
        90,
        240,
        "Generate invoice PDFs for all accounts",
    ),
    (
        "BILL-INVOICE-XMIT",
        "monthly",
        "05:00",
        45,
        120,
        "Transmit invoices via email and EDI",
    ),
    (
        "BILL-PAYMENT-MATCH",
        "daily",
        "08:00",
        60,
        180,
        "Match incoming payments to open invoices",
    ),
    ("BILL-AR-AGING", "daily", "08:30", 30, 90, "Recalculate AR aging buckets"),
    (
        "BILL-DUNNING-RUN",
        "weekly",
        "09:00",
        60,
        150,
        "Generate dunning notices for overdue accounts",
    ),
    (
        "BILL-WRITEOFF-PROC",
        "monthly",
        "10:00",
        90,
        180,
        "Process approved accounts receivable write-offs",
    ),
    (
        "BILL-CREDIT-MEMO-GEN",
        "weekly",
        "10:00",
        30,
        90,
        "Generate credit memos for approved adjustments",
    ),
    (
        "BILL-REVENUE-RECOG",
        "monthly",
        "02:00",
        120,
        300,
        "Run revenue recognition calculation",
    ),
    # ── HR / Workforce ─────────────────────────────────────────────────────
    (
        "HR-HEADCOUNT-RPT",
        "weekly",
        "07:00",
        30,
        60,
        "Compile headcount report by department",
    ),
    (
        "HR-TURNOVER-CALC",
        "monthly",
        "08:00",
        45,
        90,
        "Calculate monthly turnover metrics",
    ),
    (
        "HR-BENEFIT-ENROLL",
        "monthly",
        "09:00",
        60,
        180,
        "Process benefit enrollment changes",
    ),
    (
        "HR-PTO-BALANCE-UPD",
        "weekly",
        "06:00",
        30,
        60,
        "Update PTO balances and accruals",
    ),
    (
        "HR-ORG-CHART-SYNC",
        "daily",
        "07:00",
        15,
        45,
        "Sync org chart from HRIS to directory",
    ),
    (
        "HR-PERFORMANCE-LOAD",
        "monthly",
        "10:00",
        60,
        180,
        "Load performance review scores to HRIS",
    ),
    (
        "HR-TRAINING-COMPLIANCE",
        "weekly",
        "08:00",
        20,
        60,
        "Report mandatory training completion rates",
    ),
    (
        "HR-POSITION-BUDGET",
        "monthly",
        "11:00",
        45,
        120,
        "Reconcile open positions to headcount budget",
    ),
    # ── Data quality ───────────────────────────────────────────────────────
    (
        "DQ-NULL-CHECK",
        "daily",
        "05:00",
        30,
        90,
        "Check for unexpected NULLs in key columns",
    ),
    (
        "DQ-REFERENTIAL-CHK",
        "daily",
        "05:30",
        45,
        120,
        "Validate referential integrity across tables",
    ),
    (
        "DQ-RANGE-VALIDATION",
        "daily",
        "06:00",
        30,
        90,
        "Validate numeric fields within expected ranges",
    ),
    (
        "DQ-DUPLICATE-SCAN",
        "daily",
        "06:30",
        60,
        180,
        "Scan for duplicate records in master tables",
    ),
    ("DQ-SCHEMA-DRIFT", "weekly", "07:00", 20, 60, "Detect schema changes vs baseline"),
    (
        "DQ-FORMAT-CHECK",
        "daily",
        "05:15",
        20,
        60,
        "Validate date and code format standards",
    ),
    (
        "DQ-COMPLETENESS-RPT",
        "daily",
        "07:00",
        30,
        90,
        "Report data completeness by domain",
    ),
    (
        "DQ-GOLDEN-RECORD-CHK",
        "weekly",
        "06:00",
        60,
        180,
        "Validate golden record accuracy in MDM",
    ),
    # ── Notification / Alerting ────────────────────────────────────────────
    (
        "NOTIF-DIGEST-BUILD",
        "daily",
        "07:00",
        15,
        45,
        "Build daily operations digest email",
    ),
    (
        "NOTIF-ALERT-SWEEP",
        "daily",
        "07:30",
        10,
        30,
        "Sweep and de-duplicate pending alerts",
    ),
    (
        "NOTIF-SLA-BREACH",
        "daily",
        "08:00",
        10,
        30,
        "Flag SLA breaches from overnight runs",
    ),
    ("NOTIF-EXEC-SUMMARY", "daily", "08:30", 20, 60, "Send executive summary email"),
    ("NOTIF-ON-CALL-PAGE", "daily", "00:05", 5, 10, "Verify on-call escalation paths"),
    (
        "NOTIF-THRESHOLD-ALERT",
        "daily",
        "06:00",
        10,
        30,
        "Evaluate metric threshold alert rules",
    ),
    (
        "NOTIF-BATCH-COMPLETE",
        "daily",
        "06:30",
        5,
        15,
        "Notify ops team of batch window close",
    ),
    # ── Pricing / Rate engine ──────────────────────────────────────────────
    ("PRICE-RATE-INGEST", "daily", "16:00", 30, 90, "Ingest market rate feed"),
    (
        "PRICE-SPREAD-CALC",
        "daily",
        "16:30",
        45,
        120,
        "Calculate product pricing spreads",
    ),
    ("PRICE-PUBLISH", "daily", "17:00", 15, 45, "Publish updated prices to product DB"),
    (
        "PRICE-HIST-ARCHIVE",
        "daily",
        "17:15",
        20,
        60,
        "Archive prior-day price snapshot",
    ),
    (
        "PRICE-COMPETITOR-INGEST",
        "weekly",
        "15:00",
        60,
        180,
        "Ingest competitor pricing feed",
    ),
    (
        "PRICE-ELASTICITY-CALC",
        "weekly",
        "16:00",
        90,
        240,
        "Calculate price elasticity by SKU",
    ),
    # ── Loan / Credit ──────────────────────────────────────────────────────
    (
        "LOAN-INTEREST-ACCR",
        "daily",
        "22:00",
        90,
        240,
        "Accrue daily interest on loan portfolio",
    ),
    (
        "LOAN-PAYMENT-APPLY",
        "daily",
        "22:30",
        60,
        180,
        "Apply received loan payments to balances",
    ),
    (
        "LOAN-DELINQ-FLAG",
        "daily",
        "23:00",
        30,
        90,
        "Flag delinquent loans by aging bucket",
    ),
    (
        "LOAN-CHARGE-OFF",
        "monthly",
        "02:00",
        90,
        240,
        "Process loan charge-off approvals",
    ),
    (
        "LOAN-REFI-SCREEN",
        "weekly",
        "03:00",
        60,
        180,
        "Screen portfolio for refinance candidates",
    ),
    (
        "LOAN-MATURITY-ALERT",
        "daily",
        "07:00",
        15,
        45,
        "Alert on loans maturing within 30 days",
    ),
    (
        "LOAN-COVENANT-CHECK",
        "weekly",
        "08:00",
        60,
        180,
        "Check commercial loan covenant compliance",
    ),
    (
        "LOAN-ESCROW-RECONCILE",
        "monthly",
        "09:00",
        90,
        240,
        "Reconcile escrow accounts to servicer",
    ),
    # ── Card / Payments ────────────────────────────────────────────────────
    (
        "CARD-AUTH-RECONCILE",
        "daily",
        "01:00",
        60,
        180,
        "Reconcile card authorizations vs settlements",
    ),
    (
        "CARD-CHARGEBACK-PROC",
        "daily",
        "09:00",
        60,
        150,
        "Process inbound chargeback disputes",
    ),
    (
        "CARD-REWARD-ACCR",
        "daily",
        "22:00",
        45,
        90,
        "Accrue reward points on qualifying transactions",
    ),
    (
        "CARD-STMT-GEN",
        "monthly",
        "04:00",
        120,
        300,
        "Generate monthly cardholder statements",
    ),
    (
        "CARD-LIMIT-REVIEW",
        "weekly",
        "05:00",
        90,
        240,
        "Review and adjust credit limits",
    ),
    (
        "CARD-NETWORK-SETTLE",
        "daily",
        "20:00",
        60,
        150,
        "Settle card transactions with network",
    ),
    (
        "CARD-FRAUD-VELOCITY",
        "daily",
        "02:00",
        30,
        90,
        "Run velocity checks on card transactions",
    ),
    (
        "CARD-PIN-MAILER-GEN",
        "weekly",
        "06:00",
        30,
        90,
        "Generate PIN mailers for new card issuances",
    ),
    # ── Tax ────────────────────────────────────────────────────────────────
    (
        "TAX-WITHHOLD-CALC",
        "weekly",
        "06:00",
        60,
        150,
        "Calculate and validate tax withholdings",
    ),
    (
        "TAX-1099-GEN",
        "monthly",
        "07:00",
        120,
        300,
        "Generate 1099 forms for reportable payments",
    ),
    ("TAX-NEXUS-CHECK", "monthly", "08:00", 60, 180, "Check sales tax nexus by state"),
    ("TAX-FILING-PREP", "monthly", "09:00", 90, 240, "Prepare tax filing packages"),
    (
        "TAX-REMITTANCE-RUN",
        "monthly",
        "10:00",
        60,
        180,
        "Execute state sales tax remittance",
    ),
    (
        "TAX-DEPRECIATION-RUN",
        "monthly",
        "11:00",
        90,
        240,
        "Calculate asset depreciation schedules",
    ),
    # ── Vendor / Procurement ───────────────────────────────────────────────
    ("VEND-INVOICE-MATCH", "daily", "10:00", 45, 120, "Match vendor invoices to POs"),
    (
        "VEND-PAYMENT-RUN",
        "weekly",
        "11:00",
        60,
        180,
        "Execute approved vendor payment run",
    ),
    (
        "VEND-CONTRACT-EXP",
        "weekly",
        "12:00",
        15,
        45,
        "Alert on expiring vendor contracts",
    ),
    (
        "VEND-SPEND-ANALYSIS",
        "monthly",
        "13:00",
        90,
        240,
        "Analyze vendor spend by category",
    ),
    (
        "VEND-1099-ACCUM",
        "monthly",
        "08:00",
        45,
        120,
        "Accumulate 1099-eligible vendor payments",
    ),
    (
        "VEND-ONBOARD-STATUS",
        "weekly",
        "09:00",
        20,
        60,
        "Report vendor onboarding pipeline status",
    ),
    (
        "VEND-CERT-VERIFY",
        "monthly",
        "10:00",
        30,
        90,
        "Verify vendor insurance certificates",
    ),
    # ── Analytics / ML ─────────────────────────────────────────────────────
    (
        "ML-CHURN-SCORE",
        "daily",
        "04:00",
        120,
        360,
        "Run customer churn prediction model",
    ),
    ("ML-LTV-CALC", "weekly", "05:00", 120, 300, "Calculate customer lifetime value"),
    (
        "ML-NEXT-BEST-OFFER",
        "daily",
        "05:30",
        90,
        240,
        "Generate next-best-offer recommendations",
    ),
    (
        "ML-FEATURE-PIPELINE",
        "daily",
        "03:00",
        120,
        360,
        "Build ML feature store from raw events",
    ),
    (
        "ML-MODEL-MONITOR",
        "daily",
        "06:00",
        30,
        90,
        "Monitor model drift on production scorecards",
    ),
    (
        "ML-PROPENSITY-SCORE",
        "weekly",
        "04:00",
        120,
        300,
        "Score customer product propensity",
    ),
    (
        "ML-ANOMALY-DETECT",
        "daily",
        "02:30",
        60,
        180,
        "Run anomaly detection on transaction flows",
    ),
    (
        "ML-RETRAIN-TRIGGER",
        "weekly",
        "03:00",
        180,
        480,
        "Evaluate and trigger model retraining",
    ),
    # ── Integration / API ──────────────────────────────────────────────────
    (
        "INTG-SFDC-SYNC",
        "daily",
        "02:00",
        45,
        120,
        "Sync accounts and opps from Salesforce",
    ),
    ("INTG-ERP-EXPORT", "daily", "03:00", 60, 180, "Export GL postings to ERP system"),
    (
        "INTG-BANK-STMT-IMP",
        "daily",
        "07:00",
        30,
        90,
        "Import bank statement files via SFTP",
    ),
    (
        "INTG-EDI-INBOUND",
        "daily",
        "08:00",
        45,
        120,
        "Process inbound EDI 850/856/810 files",
    ),
    ("INTG-EDI-OUTBOUND", "daily", "09:00", 30, 90, "Transmit outbound EDI documents"),
    (
        "INTG-API-HEALTH",
        "daily",
        "00:30",
        5,
        15,
        "Ping downstream API health endpoints",
    ),
    (
        "INTG-MARKETO-SYNC",
        "daily",
        "03:30",
        30,
        90,
        "Sync campaign responses from Marketo",
    ),
    (
        "INTG-WMS-FEED",
        "daily",
        "05:00",
        45,
        120,
        "Push order updates to warehouse system",
    ),
    (
        "INTG-SHIPPING-STATUS",
        "daily",
        "06:00",
        20,
        60,
        "Pull shipment status updates from carriers",
    ),
    (
        "INTG-TAX-ENGINE",
        "daily",
        "09:30",
        30,
        90,
        "Sync tax rate tables from tax engine",
    ),
    # ── Reconciliation ─────────────────────────────────────────────────────
    ("RECON-BANK-DAILY", "daily", "09:00", 60, 180, "Reconcile bank accounts to GL"),
    (
        "RECON-CARD-DAILY",
        "daily",
        "09:30",
        45,
        120,
        "Reconcile card processor settlements",
    ),
    (
        "RECON-INTERCO",
        "monthly",
        "10:00",
        90,
        240,
        "Intercompany reconciliation and elimination",
    ),
    ("RECON-NOSTRO", "daily", "18:00", 60, 180, "Reconcile nostro accounts"),
    ("RECON-CUSTODY", "daily", "20:00", 90, 240, "Reconcile custodian holdings"),
    (
        "RECON-SUSPENSE-CLEAR",
        "daily",
        "10:00",
        45,
        120,
        "Clear items from suspense accounts",
    ),
    (
        "RECON-CASH-POSITION",
        "daily",
        "08:00",
        30,
        90,
        "Reconcile intraday cash position",
    ),
    (
        "RECON-TRADE-CONFIRM",
        "daily",
        "19:00",
        45,
        120,
        "Match trade confirmations to bookings",
    ),
    # ── Operations ─────────────────────────────────────────────────────────
    ("OPS-RUNBOOK-CHECK", "daily", "00:10", 5, 15, "Validate daily runbook completion"),
    (
        "OPS-CAPACITY-RPT",
        "daily",
        "06:00",
        10,
        30,
        "Report compute and storage capacity",
    ),
    (
        "OPS-INCIDENT-SWEEP",
        "daily",
        "07:00",
        10,
        30,
        "Sweep open incidents for SLA compliance",
    ),
    ("OPS-CHANGE-FREEZE", "weekly", "17:00", 5, 15, "Check change freeze calendar"),
    (
        "OPS-BATCH-WINDOW-OPEN",
        "daily",
        "22:00",
        5,
        10,
        "Open nightly batch processing window",
    ),
    (
        "OPS-BATCH-WINDOW-CLOSE",
        "daily",
        "06:00",
        5,
        10,
        "Close nightly batch processing window",
    ),
    (
        "OPS-DR-HEARTBEAT",
        "daily",
        "01:00",
        5,
        15,
        "Send DR site heartbeat and verify response",
    ),
    (
        "OPS-FAILOVER-TEST",
        "weekly",
        "02:00",
        60,
        180,
        "Execute automated failover test",
    ),
    (
        "OPS-ALERT-ESCALATION",
        "daily",
        "00:15",
        5,
        15,
        "Check unacknowledged alert escalation queue",
    ),
    # ── Treasury ───────────────────────────────────────────────────────────
    (
        "TREAS-CASH-FORECAST",
        "daily",
        "07:00",
        60,
        180,
        "Build 30-day rolling cash flow forecast",
    ),
    (
        "TREAS-INVEST-SWEEP",
        "daily",
        "16:00",
        30,
        90,
        "Sweep excess cash to overnight investments",
    ),
    (
        "TREAS-INVEST-MATURE",
        "daily",
        "09:00",
        20,
        60,
        "Process maturing investment principal returns",
    ),
    (
        "TREAS-FX-HEDGE-CALC",
        "daily",
        "15:00",
        60,
        180,
        "Calculate FX hedge ratio and recommend trades",
    ),
    (
        "TREAS-LIQUIDITY-RPT",
        "daily",
        "08:00",
        30,
        90,
        "Report intraday liquidity position",
    ),
    (
        "TREAS-DEBT-SCHEDULE",
        "monthly",
        "10:00",
        60,
        180,
        "Update debt amortization schedule",
    ),
    (
        "TREAS-COVENANT-RPT",
        "monthly",
        "11:00",
        45,
        120,
        "Produce debt covenant compliance report",
    ),
    # ── Fixed Assets ───────────────────────────────────────────────────────
    (
        "FA-DEPRECIATION-RUN",
        "monthly",
        "01:00",
        120,
        300,
        "Run monthly fixed asset depreciation",
    ),
    (
        "FA-ADDITION-POST",
        "monthly",
        "02:00",
        60,
        180,
        "Post new asset additions to FA register",
    ),
    (
        "FA-DISPOSAL-PROC",
        "monthly",
        "03:00",
        45,
        120,
        "Process asset disposals and retirements",
    ),
    ("FA-IMPAIRMENT-TEST", "monthly", "04:00", 90, 240, "Run asset impairment testing"),
    (
        "FA-PHYSICAL-VERIFY",
        "monthly",
        "05:00",
        60,
        180,
        "Reconcile physical asset count to register",
    ),
    # ── Audit / Controls ───────────────────────────────────────────────────
    (
        "AUDIT-USER-ACCESS-RPT",
        "weekly",
        "06:00",
        30,
        90,
        "Report user access rights vs role matrix",
    ),
    (
        "AUDIT-PRIV-ACCOUNT-CHK",
        "daily",
        "07:00",
        15,
        45,
        "Check privileged account login activity",
    ),
    (
        "AUDIT-CHANGE-LOG-RPT",
        "daily",
        "08:00",
        20,
        60,
        "Produce application change log report",
    ),
    (
        "AUDIT-SEGREGATION-CHK",
        "weekly",
        "09:00",
        45,
        120,
        "Check segregation of duties violations",
    ),
    (
        "AUDIT-EVIDENCE-PKG",
        "monthly",
        "10:00",
        90,
        240,
        "Package audit evidence for external auditors",
    ),
    # ── Customer Service / CX ──────────────────────────────────────────────
    ("CX-CSAT-LOAD", "daily", "08:00", 20, 60, "Load CSAT survey responses to DW"),
    (
        "CX-NPS-CALC",
        "weekly",
        "09:00",
        30,
        90,
        "Calculate Net Promoter Score by segment",
    ),
    (
        "CX-ESCALATION-RPT",
        "daily",
        "09:00",
        15,
        45,
        "Report open escalations by age and owner",
    ),
    (
        "CX-CONTACT-VOLUME-RPT",
        "daily",
        "07:00",
        15,
        45,
        "Report contact center volume by channel",
    ),
    (
        "CX-RESOLUTION-RATE",
        "daily",
        "08:30",
        20,
        60,
        "Calculate first-contact resolution rate",
    ),
    (
        "CX-TICKET-AGING",
        "daily",
        "10:00",
        15,
        45,
        "Age open support tickets and SLA flag",
    ),
    # ── Supply Chain ───────────────────────────────────────────────────────
    ("SC-DEMAND-FORECAST", "daily", "04:00", 90, 240, "Run demand forecasting model"),
    (
        "SC-PURCHASE-ORDER-GEN",
        "daily",
        "05:00",
        45,
        120,
        "Auto-generate purchase orders from reorder rules",
    ),
    (
        "SC-SUPPLIER-SCORECARD",
        "weekly",
        "06:00",
        60,
        180,
        "Calculate supplier on-time delivery scorecard",
    ),
    (
        "SC-LEAD-TIME-UPDATE",
        "weekly",
        "07:00",
        30,
        90,
        "Update supplier lead times in planning system",
    ),
    (
        "SC-STOCKOUT-ALERT",
        "daily",
        "06:30",
        15,
        45,
        "Alert on projected stockouts within lead time",
    ),
    (
        "SC-RETURNS-PROC",
        "daily",
        "10:00",
        45,
        120,
        "Process customer return authorizations",
    ),
    # ── Digital / E-Commerce ───────────────────────────────────────────────
    (
        "ECOMM-ORDER-EXPORT",
        "daily",
        "01:00",
        30,
        90,
        "Export online orders to fulfillment system",
    ),
    (
        "ECOMM-CATALOG-SYNC",
        "daily",
        "02:00",
        45,
        120,
        "Sync product catalog to storefront",
    ),
    (
        "ECOMM-PROMO-ACTIVATE",
        "daily",
        "00:01",
        10,
        30,
        "Activate scheduled promotions and pricing rules",
    ),
    (
        "ECOMM-CART-ABANDON",
        "daily",
        "08:00",
        20,
        60,
        "Trigger abandoned cart re-engagement emails",
    ),
    (
        "ECOMM-REVIEW-MODERATION",
        "daily",
        "09:00",
        15,
        45,
        "Queue product reviews for moderation",
    ),
    (
        "ECOMM-SITEMAP-GEN",
        "weekly",
        "02:00",
        20,
        60,
        "Regenerate XML sitemap for SEO crawl",
    ),
    # ── Security ───────────────────────────────────────────────────────────
    (
        "SEC-VULN-SCAN",
        "weekly",
        "01:00",
        120,
        300,
        "Run vulnerability scan on application hosts",
    ),
    (
        "SEC-PENTEST-REPORT",
        "monthly",
        "09:00",
        60,
        180,
        "Compile penetration test finding report",
    ),
    (
        "SEC-LOG-SIEM-EXPORT",
        "daily",
        "01:00",
        30,
        90,
        "Export security logs to SIEM platform",
    ),
    (
        "SEC-FIREWALL-REVIEW",
        "weekly",
        "08:00",
        45,
        120,
        "Review firewall rule changes for approval",
    ),
    (
        "SEC-ENDPOINT-COMPLIANCE",
        "daily",
        "06:00",
        20,
        60,
        "Check endpoint protection compliance status",
    ),
    (
        "SEC-SECRET-ROTATION",
        "monthly",
        "03:00",
        30,
        90,
        "Rotate application secrets and API keys",
    ),
    (
        "SEC-ACCESS-CERTIFY",
        "monthly",
        "10:00",
        90,
        240,
        "Run quarterly user access certification",
    ),
    # ── Product / Catalog ──────────────────────────────────────────────────
    (
        "CAT-ATTR-ENRICH",
        "daily",
        "03:00",
        45,
        120,
        "Enrich product attributes from vendor feeds",
    ),
    (
        "CAT-IMAGE-PROCESS",
        "daily",
        "04:00",
        60,
        180,
        "Process and resize product images",
    ),
    (
        "CAT-PRICE-UPDATE",
        "daily",
        "05:00",
        30,
        90,
        "Apply approved price changes to catalog",
    ),
    (
        "CAT-DISCONTINUE-SWEEP",
        "weekly",
        "06:00",
        20,
        60,
        "Flag and retire discontinued SKUs",
    ),
    (
        "CAT-TAXONOMY-VALIDATE",
        "weekly",
        "07:00",
        30,
        90,
        "Validate product taxonomy assignments",
    ),
    # ── Finance / Close ────────────────────────────────────────────────────
    ("FIN-MONTH-END-OPEN", "monthly", "00:01", 10, 30, "Open new accounting period"),
    (
        "FIN-ACCRUAL-POST",
        "monthly",
        "01:00",
        90,
        240,
        "Post month-end accrual journal entries",
    ),
    ("FIN-PREPAID-AMORT", "monthly", "02:00", 60, 180, "Amortize prepaid expenses"),
    (
        "FIN-INTERCO-ELIM",
        "monthly",
        "03:00",
        90,
        240,
        "Post intercompany elimination entries",
    ),
    (
        "FIN-CONSOL-ROLL",
        "monthly",
        "04:00",
        120,
        360,
        "Roll up consolidated financial statements",
    ),
    (
        "FIN-VARIANCE-ANALYSIS",
        "monthly",
        "05:00",
        90,
        240,
        "Produce budget vs actual variance analysis",
    ),
    ("FIN-PERIOD-LOCK", "monthly", "06:00", 10, 30, "Lock closed accounting period"),
    # ── Collections / Deposits ─────────────────────────────────────────────
    (
        "DEP-LOCKBOX-IMPORT",
        "daily",
        "07:00",
        30,
        90,
        "Import lockbox deposit files from bank",
    ),
    (
        "DEP-REMOTE-CAPTURE",
        "daily",
        "08:00",
        20,
        60,
        "Process remote deposit capture items",
    ),
    (
        "DEP-HOLDS-RELEASE",
        "daily",
        "09:00",
        15,
        45,
        "Release eligible deposit holds per Reg CC",
    ),
    (
        "DEP-INTEREST-POST",
        "monthly",
        "01:00",
        45,
        120,
        "Post monthly interest to deposit accounts",
    ),
    (
        "DEP-STMT-CYCLE",
        "monthly",
        "03:00",
        90,
        240,
        "Run monthly deposit statement cycle",
    ),
    # ── Investments / Portfolio ────────────────────────────────────────────
    (
        "PORT-REBALANCE-CALC",
        "weekly",
        "05:00",
        90,
        240,
        "Calculate portfolio rebalancing trades",
    ),
    (
        "PORT-PERFORMANCE-ATTR",
        "daily",
        "20:00",
        60,
        180,
        "Run performance attribution analysis",
    ),
    ("PORT-BENCHMARK-LOAD", "daily", "19:00", 20, 60, "Load benchmark index returns"),
    (
        "PORT-DIVIDEND-ACCR",
        "daily",
        "21:00",
        30,
        90,
        "Accrue dividends on equity holdings",
    ),
    (
        "PORT-CORP-ACTION-PROC",
        "daily",
        "18:00",
        45,
        120,
        "Process corporate actions on portfolio",
    ),
    # ── Insurance ─────────────────────────────────────────────────────────
    (
        "INS-PREMIUM-BILL",
        "monthly",
        "02:00",
        60,
        180,
        "Generate insurance premium billing",
    ),
    ("INS-CLAIMS-INTAKE", "daily", "08:00", 30, 90, "Process inbound insurance claims"),
    (
        "INS-RESERVE-CALC",
        "monthly",
        "03:00",
        90,
        240,
        "Calculate loss reserve estimates",
    ),
    ("INS-POLICY-RENEW", "daily", "07:00", 20, 60, "Flag policies due for renewal"),
    # ── Real Estate / Facilities ───────────────────────────────────────────
    (
        "FAC-LEASE-ABSTRACT",
        "monthly",
        "09:00",
        60,
        180,
        "Abstract lease terms to obligations table",
    ),
    ("FAC-RENT-PAYMENT", "monthly", "01:00", 30, 90, "Process monthly rent payments"),
    (
        "FAC-UTIL-INVOICE",
        "monthly",
        "02:00",
        45,
        120,
        "Match and post utility invoices",
    ),
    (
        "FAC-MAINTENANCE-WO",
        "weekly",
        "07:00",
        20,
        60,
        "Generate preventive maintenance work orders",
    ),
    # ── Project / Cost Accounting ──────────────────────────────────────────
    (
        "COST-LABOR-ALLOCATE",
        "weekly",
        "08:00",
        60,
        180,
        "Allocate labor costs to projects",
    ),
    (
        "COST-OVERHEAD-SPREAD",
        "monthly",
        "02:00",
        90,
        240,
        "Spread overhead costs to cost centers",
    ),
    (
        "COST-WIP-CALC",
        "monthly",
        "03:00",
        60,
        180,
        "Calculate work-in-progress balances",
    ),
    (
        "COST-VARIANCE-POST",
        "monthly",
        "04:00",
        45,
        120,
        "Post standard cost variances to GL",
    ),
    # ── Export / Trade Compliance ──────────────────────────────────────────
    (
        "TRADE-SANCTION-SCREEN",
        "daily",
        "06:00",
        30,
        90,
        "Screen transactions against sanctions lists",
    ),
    (
        "TRADE-EXPORT-LICENSE",
        "weekly",
        "07:00",
        20,
        60,
        "Check export license requirements",
    ),
    (
        "TRADE-CUSTOMS-FILING",
        "daily",
        "10:00",
        30,
        90,
        "Prepare and submit customs filing data",
    ),
    # ── Subscription / SaaS Ops ────────────────────────────────────────────
    (
        "SUBS-RENEWAL-QUEUE",
        "daily",
        "07:00",
        15,
        45,
        "Queue upcoming subscription renewals",
    ),
    ("SUBS-CHURN-FLAG", "daily", "08:00", 20, 60, "Flag subscriptions at churn risk"),
    (
        "SUBS-USAGE-METER",
        "daily",
        "01:00",
        30,
        90,
        "Meter per-seat and usage-based consumption",
    ),
    (
        "SUBS-TRIAL-EXPIRE",
        "daily",
        "00:30",
        10,
        30,
        "Expire trials and trigger conversion flows",
    ),
    # ── Grants / Non-Profit ────────────────────────────────────────────────
    (
        "GRANT-EXPENSE-ALLOC",
        "monthly",
        "02:00",
        60,
        180,
        "Allocate expenses to grant cost centers",
    ),
    (
        "GRANT-DRAWDOWN-REQ",
        "monthly",
        "03:00",
        45,
        120,
        "Prepare grant drawdown requests",
    ),
    (
        "GRANT-REPORT-COMPILE",
        "monthly",
        "04:00",
        90,
        240,
        "Compile funder progress reports",
    ),
    # ── Miscellaneous Ops ──────────────────────────────────────────────────
    (
        "OPS-TIMEZONE-ROLLOVER",
        "daily",
        "00:00",
        5,
        10,
        "Execute timezone rollover housekeeping",
    ),
    ("OPS-SEQUENCE-RESET", "daily", "00:01", 5, 10, "Reset daily sequence counters"),
]

# Prerequisite wiring
PREREQ_PAIRS = [
    # Settlement chain
    (0, 1),
    (1, 2),
    (2, 3),
    (3, 4),
    (4, 5),
    (5, 6),
    (6, 7),
    # GL close chain
    (8, 9),
    (9, 10),
    (10, 11),
    (11, 12),
    (12, 13),
    # Payroll chain
    (14, 15),
    (15, 16),
    (16, 17),
    (17, 18),
    (18, 19),
    (14, 20),
    (17, 21),
    # ACH chain
    (22, 23),
    (24, 25),
    (25, 26),
    (26, 27),
    (27, 28),
    (24, 29),
    # Customer pipeline
    (30, 31),
    (31, 32),
    (32, 33),
    (33, 34),
    # ETL chains
    (59, 60),
    (60, 61),
    (62, 63),
    (63, 64),
    (65, 66),
    # Fraud chain
    (78, 79),
    (79, 80),
    # Billing chain
    (103, 104),
    (104, 105),
    (106, 107),
    # Data quality chain
    (126, 127),
    (127, 128),
    (128, 129),
    # Loan chain
    (172, 173),
    (173, 174),
    # Recon chain
    (198, 199),
    (203, 204),
    # Finance close chain
    (285, 286),
    (286, 287),
    (287, 288),
    (288, 289),
    (289, 290),
    (290, 291),
    # Treasury chain
    (221, 222),
    # ML pipeline
    (244, 245),
    (245, 246),
    # ETL event
    (59, 67),
]

ERROR_TYPES = {
    "timeout": "Job exceeded 10 minute execution limit",
    "resource_error": "Insufficient memory available",
    "dependency_error": "Required prerequisite job failed",
    "io_error": "Database connection timeout",
}

CLIENTS = ["Acme Corp", "TechCo Inc", "RetailMart", "Warehouse LLC", "FinServ Group"]

JOB_TEMPLATES = [
    {"name": "Daily Sales Report", "duration_range": (60, 300)},
    {"name": "Customer Data Sync", "duration_range": (30, 180)},
    {"name": "Invoice Processing", "duration_range": (120, 600)},
    {"name": "Inventory Update", "duration_range": (45, 240)},
    {"name": "Payment Reconciliation", "duration_range": (90, 480)},
    {"name": "Data Backup", "duration_range": (180, 900)},
    {"name": "System Health Check", "duration_range": (15, 60)},
    {"name": "Generate Analytics Dashboard", "duration_range": (60, 360)},
    {"name": "ETL Pipeline Run", "duration_range": (120, 720)},
    {"name": "End-of-Day Settlement", "duration_range": (300, 1200)},
    {"name": "Customer Report Export", "duration_range": (60, 300)},
    {"name": "Archive Old Records", "duration_range": (90, 540)},
]


def seed():
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS jobs (
            id SERIAL PRIMARY KEY,
            job_id TEXT UNIQUE NOT NULL,
            job_name TEXT NOT NULL,
            client TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'queued',
            start_time TEXT,
            end_time TEXT,
            duration INTEGER,
            progress INTEGER DEFAULT 0,
            error_message TEXT,
            error_type TEXT,
            retry_count INTEGER DEFAULT 0,
            max_retries INTEGER DEFAULT 2,
            depends_on_job_id TEXT,
            logs TEXT DEFAULT '',
            triggered_by TEXT DEFAULT 'system',
            created_at TEXT NOT NULL
        )
    """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS tasks (
            id SERIAL PRIMARY KEY,
            task_id TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            schedule TEXT NOT NULL,
            scheduled_time TEXT NOT NULL,
            duration_min INTEGER NOT NULL,
            duration_max INTEGER NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            prerequisite_task_id TEXT,
            description TEXT,
            created_at TEXT NOT NULL
        )
    """
    )
    conn.commit()

    # ── jobs ───────────────────────────────────────────────────────────────
    cur.execute("DELETE FROM jobs")
    now = datetime.utcnow()
    jobs = []
    for _ in range(315):
        template = random.choice(JOB_TEMPLATES)
        client = random.choice(CLIENTS)
        created_at = now - timedelta(
            hours=random.randint(0, 48), minutes=random.randint(0, 59)
        )
        status = random.choices(
            ["completed", "failed", "running", "queued"], weights=[55, 15, 20, 10]
        )[0]
        start_time = end_time = None
        duration = progress = 0
        error_message = error_type = None
        retry_count = 0

        if status == "completed":
            start_time = created_at + timedelta(seconds=random.randint(5, 30))
            duration = random.randint(*template["duration_range"])
            end_time = start_time + timedelta(seconds=duration)
            progress = 100
        elif status == "failed":
            start_time = created_at + timedelta(seconds=random.randint(5, 30))
            duration = random.randint(10, template["duration_range"][0])
            end_time = start_time + timedelta(seconds=duration)
            progress = random.randint(10, 80)
            err_key = random.choice(list(ERROR_TYPES.keys()))
            error_type = err_key
            error_message = ERROR_TYPES[err_key]
            retry_count = random.randint(0, 2)
        elif status == "running":
            start_time = created_at + timedelta(seconds=random.randint(5, 30))
            progress = random.randint(5, 95)

        jobs.append(
            (
                str(uuid.uuid4())[:8],
                template["name"],
                client,
                status,
                start_time.isoformat() if start_time else None,
                end_time.isoformat() if end_time else None,
                duration,
                progress,
                error_message,
                error_type,
                retry_count,
                2,
                None,
                "",
                "system",
                created_at.isoformat(),
            )
        )

    cur.executemany(
        """
        INSERT INTO jobs (
            job_id, job_name, client, status,
            start_time, end_time, duration, progress,
            error_message, error_type, retry_count, max_retries,
            depends_on_job_id, logs, triggered_by, created_at
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """,
        jobs,
    )
    print(f"[Seed] Inserted {len(jobs)} jobs")

    # ── tasks ──────────────────────────────────────────────────────────────
    cur.execute("DELETE FROM tasks")
    task_ids = [str(uuid.uuid4())[:8] for _ in TASK_DEFINITIONS]
    now_str = now.isoformat()

    prereq_map = {}
    for prereq_idx, dep_idx in PREREQ_PAIRS:
        if dep_idx < len(TASK_DEFINITIONS):
            prereq_map[dep_idx] = task_ids[prereq_idx]

    task_rows = []
    for i, (name, schedule, sched_time, dur_min, dur_max, desc) in enumerate(
        TASK_DEFINITIONS
    ):
        task_rows.append(
            (
                task_ids[i],
                name,
                schedule,
                sched_time,
                dur_min,
                dur_max,
                True,
                prereq_map.get(i),
                desc,
                now_str,
            )
        )

    cur.executemany(
        """
        INSERT INTO tasks (
            task_id, name, schedule, scheduled_time,
            duration_min, duration_max, enabled,
            prerequisite_task_id, description, created_at
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """,
        task_rows,
    )
    print(f"[Seed] Inserted {len(task_rows)} tasks")

    conn.commit()
    cur.close()
    conn.close()


if __name__ == "__main__":
    seed()
